### General
[vscode-extensions-activitywatch]
src.vsmarketplace = "activitywatch.aw-watcher-vscode"
fetch.vsmarketplace = "activitywatch.aw-watcher-vscode"
passthru = { publisher = "activitywatch", name = "aw-watcher-vscode"}

[vscode-extensions-ballerina]
src.vsmarketplace = "WSO2.ballerina"
fetch.vsmarketplace = "WSO2.ballerina"
passthru = { publisher = "WSO2", name = "ballerina"}

[vscode-extensions-copilot]
src.vsmarketplace = "GitHub.copilot"
fetch.vsmarketplace = "GitHub.copilot"
passthru = { publisher = "GitHub", name = "copilot"}

[vscode-extensions-multi-cursor-case-preserve]
src.vsmarketplace = "Cardinal90.multi-cursor-case-preserve"
fetch.vsmarketplace = "Cardinal90.multi-cursor-case-preserve"
passthru = { publisher = "Cardinal90", name = "multi-cursor-case-preserve"}

[vscode-extensions-tokyo-night]
src.vsmarketplace = "enkia.tokyo-night"
fetch.vsmarketplace = "enkia.tokyo-night"
passthru = { publisher = "enkia", name = "tokyo-night"}

[vscode-extensions-vscode-emacs-friendly]
src.vsmarketplace = "lfs.vscode-emacs-friendly"
fetch.vsmarketplace = "lfs.vscode-emacs-friendly"
passthru = { publisher = "lfs", name = "vscode-emacs-friendly"}

### crystal-lang
[vscode-extensions-crystal-lang]
src.vsmarketplace = "crystal-lang-tools.crystal-lang"
fetch.vsmarketplace = "crystal-lang-tools.crystal-lang"
passthru = { publisher = "crystal-lang-tools", name = "crystal-lang"}

[vscode-extensions-crystal-spec-vscode]
src.vsmarketplace = "matthewmcgarvey.crystal-spec-vscode"
fetch.vsmarketplace = "matthewmcgarvey.crystal-spec-vscode"
passthru = { publisher = "matthewmcgarvey", name = "crystal-spec-vscode"}


### nix and nix-alike
[vscode-extensions-nickel-syntax]
src.vsmarketplace = "kubukoz.nickel-syntax"
fetch.vsmarketplace = "kubukoz.nickel-syntax"
passthru = { publisher = "kubukoz", name = "nickel-syntax"}


[vscode-extensions-zeek]
src.vsmarketplace = "aeppert.bro"
fetch.vsmarketplace = "aeppert.bro"
passthru = { publisher = "aeppert", name = "bro"}

[vscode-extensions-readable-indent]
src.vsmarketplace = "cnojima.readable-indent"
fetch.vsmarketplace = "cnojima.readable-indent"
passthru = { publisher = "cnojima", name = "readable-indent"}

[vscode-extensions-indent-rainbow]
src.vsmarketplace = "oderwat.indent-rainbow"
fetch.vsmarketplace = "oderwat.indent-rainbow"
passthru = { publisher = "oderwat", name = "indent-rainbow"}

[vscode-extensions-tabnine-vscode]
src.vsmarketplace = "TabNine.tabnine-vscode"
fetch.vsmarketplace = "TabNine.tabnine-vscode"
passthru = { publisher = "TabNine", name = "tabnine-vscode"}

[vscode-extensions-pdf]
src.vsmarketplace = "tomoki1207.pdf"
fetch.vsmarketplace = "tomoki1207.pdf"
passthru = { publisher = "tomoki1207", name = "pdf"}

[vscode-extensions-language-julia]
src.vsmarketplace = "julialang.language-julia"
fetch.vsmarketplace = "julialang.language-julia"
passthru = { publisher = "julialang", name = "language-julia"}

[vscode-extensions-julia-color-themes]
src.vsmarketplace = "cameronbieganek.julia-color-themes"
fetch.vsmarketplace = "cameronbieganek.julia-color-themes"
passthru = { publisher = "cameronbieganek", name = "julia-color-themes"}

[vscode-extensions-vscode-markdownlint]
src.vsmarketplace = "DavidAnson.vscode-markdownlint"
fetch.vsmarketplace = "DavidAnson.vscode-markdownlint"
passthru = { publisher = "DavidAnson", name = "vscode-markdownlint"}

[vscode-extensions-markdown-preview-enhanced]
src.vsmarketplace = "shd101wyy.markdown-preview-enhanced"
fetch.vsmarketplace = "shd101wyy.markdown-preview-enhanced"
passthru = { publisher = "shd101wyy", name = "markdown-preview-enhanced"}

[vscode-extensions-vscode-docker]
src.vsmarketplace = "ms-azuretools.vscode-docker"
fetch.vsmarketplace = "ms-azuretools.vscode-docker"
passthru = { publisher = "ms-azuretools", name = "vscode-docker"}

[vscode-extensions-Ruby]
src.vsmarketplace = "rebornix.Ruby"
fetch.vsmarketplace ="rebornix.Ruby"
passthru = { publisher = "rebornix", name = "Ruby"}

[vscode-extensions-vscode-ruby]
src.vsmarketplace = "wingrunr21.vscode-ruby"
fetch.vsmarketplace = "wingrunr21.vscode-ruby"
passthru = { publisher = "wingrunr21", name = "vscode-ruby"}

[vscode-extensions-solargraph]
src.vsmarketplace = "castwide.solargraph"
fetch.vsmarketplace = "castwide.solargraph"
passthru = { publisher = "castwide", name = "solargraph"}

[vscode-extensions-rails-snippets]
src.vsmarketplace = "hridoy.rails-snippets"
fetch.vsmarketplace = "hridoy.rails-snippets"
passthru = { publisher = "hridoy", name = "rails-snippets"}

[vscode-extensions-ruby-rubocop]
src.vsmarketplace = "misogi.ruby-rubocop"
fetch.vsmarketplace ="misogi.ruby-rubocop"
passthru = { publisher = "misogi", name = "ruby-rubocop"}

[vscode-extensions-ruby]
src.vsmarketplace = "groksrc.ruby"
fetch.vsmarketplace = "groksrc.ruby"
passthru = { publisher = "groksrc", name = "ruby"}

[vscode-extensions-haml]
src.vsmarketplace = "vayan.haml"
fetch.vsmarketplace = "vayan.haml"
passthru = { publisher = "vayan", name = "haml"}

[vscode-extensions-simple-ruby-erb]
src.vsmarketplace = "vortizhe.simple-ruby-erb"
fetch.vsmarketplace = "vortizhe.simple-ruby-erb"
passthru = { publisher = "vortizhe", name = "simple-ruby-erb"}

[vscode-extensions-ruby-linter]
src.vsmarketplace = "hoovercj.ruby-linter"
fetch.vsmarketplace = "hoovercj.ruby-linter"
passthru = { publisher = "hoovercj", name = "ruby-linter"}

[vscode-extensions-ruby-symbols]
src.vsmarketplace = "miguel-savignano.ruby-symbols"
fetch.vsmarketplace = "miguel-savignano.ruby-symbols"
passthru = { publisher = "miguel-savignano", name = "ruby-symbols"}

[vscode-extensions-emacs-mcx]
src.vsmarketplace = "tuttieee.emacs-mcx"
fetch.vsmarketplace = "tuttieee.emacs-mcx"
passthru = { publisher = "tuttieee", name = "emacs-mcx"}

[vscode-extensions-vscode-emacs-tab]
src.vsmarketplace = "garaemon.vscode-emacs-tab"
fetch.vsmarketplace = "garaemon.vscode-emacs-tab"
passthru = { publisher = "garaemon", name = "vscode-emacs-tab"}

[vscode-extensions-remote-ssh-edit]
src.vsmarketplace = "ms-vscode-remote.remote-ssh-edit"
fetch.vsmarketplace = "ms-vscode-remote.remote-ssh-edit"
passthru = { publisher = "ms-vscode-remote", name = "remote-ssh-edit"}

#######
[vscode-extensions-cucumberautocomplete]
src.vsmarketplace = "alexkrechik.cucumberautocomplete"
fetch.vsmarketplace = "alexkrechik.cucumberautocomplete"
passthru = { publisher = "alexkrechik", name = "cucumberautocomplete"}

[vscode-extensions-gherkintablealign]
src.vsmarketplace = "AlanCole.gherkintablealign"
fetch.vsmarketplace = "AlanCole.gherkintablealign"
passthru = { publisher = "AlanCole", name = "gherkintablealign"}

[vscode-extensions-vscode-direnv]
src.vsmarketplace = "cab404.vscode-direnv"
fetch.vsmarketplace = "cab404.vscode-direnv"
passthru = { publisher = "cab404", name = "vscode-direnv"}

[vscode-extensions-nix-extension-pack]
src.vsmarketplace = "pinage404.nix-extension-pack"
fetch.vsmarketplace = "pinage404.nix-extension-pack"
passthru = { publisher = "pinage404", name = "nix-extension-pack"}

[vscode-extensions-nix-ide]
src.vsmarketplace = "jnoortheen.nix-ide"
fetch.vsmarketplace = "jnoortheen.nix-ide"
passthru = { publisher = "jnoortheen", name = "nix-ide"}

[vscode-extensions-even-better-toml]
src.vsmarketplace = "tamasfe.even-better-toml"
fetch.vsmarketplace = "tamasfe.even-better-toml"
passthru = { publisher = "tamasfe", name = "even-better-toml"}

