# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  vscode-extensions-Ruby = {
    pname = "vscode-extensions-Ruby";
    version = "0.28.1";
    src = fetchurl {
      url = "https://rebornix.gallery.vsassets.io/_apis/public/gallery/publisher/rebornix/extension/Ruby/0.28.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "Ruby-0.28.1.zip";
      sha256 = "sha256-HAUdv+2T+neJ5aCGiQ37pCO6x6r57HIUnLm4apg9L50=";
    };
    name = "Ruby";
    publisher = "rebornix";
  };
  vscode-extensions-activitywatch = {
    pname = "vscode-extensions-activitywatch";
    version = "0.5.0";
    src = fetchurl {
      url = "https://activitywatch.gallery.vsassets.io/_apis/public/gallery/publisher/activitywatch/extension/aw-watcher-vscode/0.5.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "aw-watcher-vscode-0.5.0.zip";
      sha256 = "sha256-OrdIhgNXpEbLXYVJAx/jpt2c6Qa5jf8FNxqrbu5FfFs=";
    };
    name = "aw-watcher-vscode";
    publisher = "activitywatch";
  };
  vscode-extensions-ballerina = {
    pname = "vscode-extensions-ballerina";
    version = "3.3.6";
    src = fetchurl {
      url = "https://WSO2.gallery.vsassets.io/_apis/public/gallery/publisher/WSO2/extension/ballerina/3.3.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ballerina-3.3.6.zip";
      sha256 = "sha256-mbXS29tKqE7mHqad+JUB5ZHc4RQRQME/q+JyftapEgo=";
    };
    name = "ballerina";
    publisher = "WSO2";
  };
  vscode-extensions-copilot = {
    pname = "vscode-extensions-copilot";
    version = "1.70.8099";
    src = fetchurl {
      url = "https://GitHub.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/copilot/1.70.8099/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-1.70.8099.zip";
      sha256 = "sha256-+jlLM9UC1DZFBrtiiri4jvpuc/Rf9PcSVP8D8pmQC2s=";
    };
    name = "copilot";
    publisher = "GitHub";
  };
  vscode-extensions-crystal-lang = {
    pname = "vscode-extensions-crystal-lang";
    version = "0.8.4";
    src = fetchurl {
      url = "https://crystal-lang-tools.gallery.vsassets.io/_apis/public/gallery/publisher/crystal-lang-tools/extension/crystal-lang/0.8.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "crystal-lang-0.8.4.zip";
      sha256 = "sha256-hU6g4CqcCxXlhqSKL36vgzX2EJ7fIdbIuPCHbpRW/zE=";
    };
    name = "crystal-lang";
    publisher = "crystal-lang-tools";
  };
  vscode-extensions-crystal-spec-vscode = {
    pname = "vscode-extensions-crystal-spec-vscode";
    version = "0.1.0";
    src = fetchurl {
      url = "https://matthewmcgarvey.gallery.vsassets.io/_apis/public/gallery/publisher/matthewmcgarvey/extension/crystal-spec-vscode/0.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "crystal-spec-vscode-0.1.0.zip";
      sha256 = "sha256-3plr6exbkkaCSEcw766MFFI30NeQp+WNi1aAD4SpTT0=";
    };
    name = "crystal-spec-vscode";
    publisher = "matthewmcgarvey";
  };
  vscode-extensions-cucumberautocomplete = {
    pname = "vscode-extensions-cucumberautocomplete";
    version = "2.15.2";
    src = fetchurl {
      url = "https://alexkrechik.gallery.vsassets.io/_apis/public/gallery/publisher/alexkrechik/extension/cucumberautocomplete/2.15.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cucumberautocomplete-2.15.2.zip";
      sha256 = "sha256-MdBJ71fIkIVOhLCoF/6/CATmUvutiTJPrIoVeb/eXc0=";
    };
    name = "cucumberautocomplete";
    publisher = "alexkrechik";
  };
  vscode-extensions-emacs-mcx = {
    pname = "vscode-extensions-emacs-mcx";
    version = "0.47.0";
    src = fetchurl {
      url = "https://tuttieee.gallery.vsassets.io/_apis/public/gallery/publisher/tuttieee/extension/emacs-mcx/0.47.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "emacs-mcx-0.47.0.zip";
      sha256 = "sha256-dGty5+1+JEtJgl/DiyqEB/wuf3K8tCj1qWKua6ongIs=";
    };
    name = "emacs-mcx";
    publisher = "tuttieee";
  };
  vscode-extensions-even-better-toml = {
    pname = "vscode-extensions-even-better-toml";
    version = "0.19.0";
    src = fetchurl {
      url = "https://tamasfe.gallery.vsassets.io/_apis/public/gallery/publisher/tamasfe/extension/even-better-toml/0.19.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "even-better-toml-0.19.0.zip";
      sha256 = "sha256-MqSQarNThbEf1wHDTf1yA46JMhWJN46b08c7tV6+1nU=";
    };
    name = "even-better-toml";
    publisher = "tamasfe";
  };
  vscode-extensions-gherkintablealign = {
    pname = "vscode-extensions-gherkintablealign";
    version = "1.0.2";
    src = fetchurl {
      url = "https://AlanCole.gallery.vsassets.io/_apis/public/gallery/publisher/AlanCole/extension/gherkintablealign/1.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gherkintablealign-1.0.2.zip";
      sha256 = "sha256-AhCm/GyleEOW9NlzE9uSJKIjM8RKQBjSM+RS1j3jiRM=";
    };
    name = "gherkintablealign";
    publisher = "AlanCole";
  };
  vscode-extensions-haml = {
    pname = "vscode-extensions-haml";
    version = "1.0.1";
    src = fetchurl {
      url = "https://vayan.gallery.vsassets.io/_apis/public/gallery/publisher/vayan/extension/haml/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "haml-1.0.1.zip";
      sha256 = "sha256-KTsKUfo7bfwqVMSAjRYuPuk+K5Qk+jBlHBlHWTunCdI=";
    };
    name = "haml";
    publisher = "vayan";
  };
  vscode-extensions-indent-rainbow = {
    pname = "vscode-extensions-indent-rainbow";
    version = "8.3.1";
    src = fetchurl {
      url = "https://oderwat.gallery.vsassets.io/_apis/public/gallery/publisher/oderwat/extension/indent-rainbow/8.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "indent-rainbow-8.3.1.zip";
      sha256 = "sha256-dOicya0B2sriTcDSdCyhtp0Mcx5b6TUaFKVb0YU3jUc=";
    };
    name = "indent-rainbow";
    publisher = "oderwat";
  };
  vscode-extensions-julia-color-themes = {
    pname = "vscode-extensions-julia-color-themes";
    version = "0.1.1";
    src = fetchurl {
      url = "https://cameronbieganek.gallery.vsassets.io/_apis/public/gallery/publisher/cameronbieganek/extension/julia-color-themes/0.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "julia-color-themes-0.1.1.zip";
      sha256 = "sha256-22TA7RpC0W3G8uA4EIqeuB4gqDF9cr1gNS+u7qQ3IaA=";
    };
    name = "julia-color-themes";
    publisher = "cameronbieganek";
  };
  vscode-extensions-language-julia = {
    pname = "vscode-extensions-language-julia";
    version = "1.41.1";
    src = fetchurl {
      url = "https://julialang.gallery.vsassets.io/_apis/public/gallery/publisher/julialang/extension/language-julia/1.41.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "language-julia-1.41.1.zip";
      sha256 = "sha256-h/8/YcqaJgL8GiqXBBXMQ5TSYU7Rn/hr39jPvyfL1KA=";
    };
    name = "language-julia";
    publisher = "julialang";
  };
  vscode-extensions-markdown-preview-enhanced = {
    pname = "vscode-extensions-markdown-preview-enhanced";
    version = "0.6.7";
    src = fetchurl {
      url = "https://shd101wyy.gallery.vsassets.io/_apis/public/gallery/publisher/shd101wyy/extension/markdown-preview-enhanced/0.6.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "markdown-preview-enhanced-0.6.7.zip";
      sha256 = "sha256-5tgxpjkpbgv8HcfLBbDcOOEd8swinK5iHtnO34892ik=";
    };
    name = "markdown-preview-enhanced";
    publisher = "shd101wyy";
  };
  vscode-extensions-multi-cursor-case-preserve = {
    pname = "vscode-extensions-multi-cursor-case-preserve";
    version = "1.0.5";
    src = fetchurl {
      url = "https://Cardinal90.gallery.vsassets.io/_apis/public/gallery/publisher/Cardinal90/extension/multi-cursor-case-preserve/1.0.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "multi-cursor-case-preserve-1.0.5.zip";
      sha256 = "sha256-eJafjYDydD8DW83VLH9MPFeDENXBx3el7XvjZqu88Jw=";
    };
    name = "multi-cursor-case-preserve";
    publisher = "Cardinal90";
  };
  vscode-extensions-nickel-syntax = {
    pname = "vscode-extensions-nickel-syntax";
    version = "0.0.2";
    src = fetchurl {
      url = "https://kubukoz.gallery.vsassets.io/_apis/public/gallery/publisher/kubukoz/extension/nickel-syntax/0.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nickel-syntax-0.0.2.zip";
      sha256 = "sha256-ffPZd717Y2OF4d9MWE6zKwcsGWS90ZJvhWkqP831tVM=";
    };
    name = "nickel-syntax";
    publisher = "kubukoz";
  };
  vscode-extensions-nix-extension-pack = {
    pname = "vscode-extensions-nix-extension-pack";
    version = "3.0.0";
    src = fetchurl {
      url = "https://pinage404.gallery.vsassets.io/_apis/public/gallery/publisher/pinage404/extension/nix-extension-pack/3.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-extension-pack-3.0.0.zip";
      sha256 = "sha256-cWXd6AlyxBroZF+cXZzzWZbYPDuOqwCZIK67cEP5sNk=";
    };
    name = "nix-extension-pack";
    publisher = "pinage404";
  };
  vscode-extensions-nix-ide = {
    pname = "vscode-extensions-nix-ide";
    version = "0.2.1";
    src = fetchurl {
      url = "https://jnoortheen.gallery.vsassets.io/_apis/public/gallery/publisher/jnoortheen/extension/nix-ide/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-ide-0.2.1.zip";
      sha256 = "sha256-yC4ybThMFA2ncGhp8BYD7IrwYiDU3226hewsRvJYKy4=";
    };
    name = "nix-ide";
    publisher = "jnoortheen";
  };
  vscode-extensions-pdf = {
    pname = "vscode-extensions-pdf";
    version = "1.2.2";
    src = fetchurl {
      url = "https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pdf-1.2.2.zip";
      sha256 = "sha256-i3Rlizbw4RtPkiEsodRJEB3AUzoqI95ohyqZ0ksROps=";
    };
    name = "pdf";
    publisher = "tomoki1207";
  };
  vscode-extensions-rails-snippets = {
    pname = "vscode-extensions-rails-snippets";
    version = "1.0.8";
    src = fetchurl {
      url = "https://hridoy.gallery.vsassets.io/_apis/public/gallery/publisher/hridoy/extension/rails-snippets/1.0.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "rails-snippets-1.0.8.zip";
      sha256 = "sha256-OSh/BhBxs4Vx5s8tTRlEIlk9sXRvpjLqZ6BqjGLgemA=";
    };
    name = "rails-snippets";
    publisher = "hridoy";
  };
  vscode-extensions-readable-indent = {
    pname = "vscode-extensions-readable-indent";
    version = "1.2.2";
    src = fetchurl {
      url = "https://cnojima.gallery.vsassets.io/_apis/public/gallery/publisher/cnojima/extension/readable-indent/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "readable-indent-1.2.2.zip";
      sha256 = "sha256-iTgbxasaNTIBlLLUPs00Y9x099zfXc6ES6drTc8CE78=";
    };
    name = "readable-indent";
    publisher = "cnojima";
  };
  vscode-extensions-remote-ssh-edit = {
    pname = "vscode-extensions-remote-ssh-edit";
    version = "0.84.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-ssh-edit/0.84.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-ssh-edit-0.84.0.zip";
      sha256 = "sha256-33jHWC8K0TWJG54m6FqnYEotKqNxkcd/D14TFz6dgmc=";
    };
    name = "remote-ssh-edit";
    publisher = "ms-vscode-remote";
  };
  vscode-extensions-ruby = {
    pname = "vscode-extensions-ruby";
    version = "0.1.0";
    src = fetchurl {
      url = "https://groksrc.gallery.vsassets.io/_apis/public/gallery/publisher/groksrc/extension/ruby/0.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-0.1.0.zip";
      sha256 = "sha256-JrkzYKjRf1bExSrZOQxek9TS+K14jcJYxjNCEqqHcdk=";
    };
    name = "ruby";
    publisher = "groksrc";
  };
  vscode-extensions-ruby-linter = {
    pname = "vscode-extensions-ruby-linter";
    version = "1.0.0";
    src = fetchurl {
      url = "https://hoovercj.gallery.vsassets.io/_apis/public/gallery/publisher/hoovercj/extension/ruby-linter/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-linter-1.0.0.zip";
      sha256 = "sha256-DqykFLOQgv10xw/Q2ZtyW1ATOhI61+IY/6lrc9/ln3w=";
    };
    name = "ruby-linter";
    publisher = "hoovercj";
  };
  vscode-extensions-ruby-rubocop = {
    pname = "vscode-extensions-ruby-rubocop";
    version = "0.8.6";
    src = fetchurl {
      url = "https://misogi.gallery.vsassets.io/_apis/public/gallery/publisher/misogi/extension/ruby-rubocop/0.8.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-rubocop-0.8.6.zip";
      sha256 = "sha256-6hgJzOerGCCXcpADnISa7ewQnRWLAn6k6K4kLJR09UI=";
    };
    name = "ruby-rubocop";
    publisher = "misogi";
  };
  vscode-extensions-ruby-symbols = {
    pname = "vscode-extensions-ruby-symbols";
    version = "0.1.8";
    src = fetchurl {
      url = "https://miguel-savignano.gallery.vsassets.io/_apis/public/gallery/publisher/miguel-savignano/extension/ruby-symbols/0.1.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-symbols-0.1.8.zip";
      sha256 = "sha256-3IsqJ46IG0O2g7hKBt0OgQwruaGu9TuA3XpjAjAk550=";
    };
    name = "ruby-symbols";
    publisher = "miguel-savignano";
  };
  vscode-extensions-simple-ruby-erb = {
    pname = "vscode-extensions-simple-ruby-erb";
    version = "0.2.1";
    src = fetchurl {
      url = "https://vortizhe.gallery.vsassets.io/_apis/public/gallery/publisher/vortizhe/extension/simple-ruby-erb/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "simple-ruby-erb-0.2.1.zip";
      sha256 = "sha256-JZov46QWUHIewu4FZtlQL/wRV6rHpu6Kd9yuWdCL77w=";
    };
    name = "simple-ruby-erb";
    publisher = "vortizhe";
  };
  vscode-extensions-solargraph = {
    pname = "vscode-extensions-solargraph";
    version = "0.24.0";
    src = fetchurl {
      url = "https://castwide.gallery.vsassets.io/_apis/public/gallery/publisher/castwide/extension/solargraph/0.24.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "solargraph-0.24.0.zip";
      sha256 = "sha256-7mMzN+OdJ5R9CVaBJMzW218wMG5ETvNrUTST9/kjjV0=";
    };
    name = "solargraph";
    publisher = "castwide";
  };
  vscode-extensions-tabnine-vscode = {
    pname = "vscode-extensions-tabnine-vscode";
    version = "3.6.36";
    src = fetchurl {
      url = "https://TabNine.gallery.vsassets.io/_apis/public/gallery/publisher/TabNine/extension/tabnine-vscode/3.6.36/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tabnine-vscode-3.6.36.zip";
      sha256 = "sha256-VCkdjM4TyQQQjwApqberwrAe64bck43EmZJZApYLOaM=";
    };
    name = "tabnine-vscode";
    publisher = "TabNine";
  };
  vscode-extensions-tokyo-night = {
    pname = "vscode-extensions-tokyo-night";
    version = "0.9.4";
    src = fetchurl {
      url = "https://enkia.gallery.vsassets.io/_apis/public/gallery/publisher/enkia/extension/tokyo-night/0.9.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tokyo-night-0.9.4.zip";
      sha256 = "sha256-pKokB6446SR6LsTHyJtQ+FEA07A0W9UAI+byqtGeMGw=";
    };
    name = "tokyo-night";
    publisher = "enkia";
  };
  vscode-extensions-vscode-direnv = {
    pname = "vscode-extensions-vscode-direnv";
    version = "1.0.0";
    src = fetchurl {
      url = "https://cab404.gallery.vsassets.io/_apis/public/gallery/publisher/cab404/extension/vscode-direnv/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-direnv-1.0.0.zip";
      sha256 = "sha256-+nLH+T9v6TQCqKZw6HPN/ZevQ65FVm2SAo2V9RecM3Y=";
    };
    name = "vscode-direnv";
    publisher = "cab404";
  };
  vscode-extensions-vscode-docker = {
    pname = "vscode-extensions-vscode-docker";
    version = "1.23.3";
    src = fetchurl {
      url = "https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-docker/1.23.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-docker-1.23.3.zip";
      sha256 = "sha256-0qflugzWA1pV0PVWGTzOjdxM/0G8hTLOozoXCAdQnRY=";
    };
    name = "vscode-docker";
    publisher = "ms-azuretools";
  };
  vscode-extensions-vscode-emacs-friendly = {
    pname = "vscode-extensions-vscode-emacs-friendly";
    version = "0.9.0";
    src = fetchurl {
      url = "https://lfs.gallery.vsassets.io/_apis/public/gallery/publisher/lfs/extension/vscode-emacs-friendly/0.9.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-friendly-0.9.0.zip";
      sha256 = "sha256-YWu2a5hz0qGZvgR95DbzUw6PUvz17i1o4+eAUM/xjMg=";
    };
    name = "vscode-emacs-friendly";
    publisher = "lfs";
  };
  vscode-extensions-vscode-emacs-tab = {
    pname = "vscode-extensions-vscode-emacs-tab";
    version = "0.1.0";
    src = fetchurl {
      url = "https://garaemon.gallery.vsassets.io/_apis/public/gallery/publisher/garaemon/extension/vscode-emacs-tab/0.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-tab-0.1.0.zip";
      sha256 = "sha256-XXBJXgbWVdoiWYnsJ2CjgNDycKPWe5XMYjVkU4QxCQA=";
    };
    name = "vscode-emacs-tab";
    publisher = "garaemon";
  };
  vscode-extensions-vscode-markdownlint = {
    pname = "vscode-extensions-vscode-markdownlint";
    version = "0.49.0";
    src = fetchurl {
      url = "https://DavidAnson.gallery.vsassets.io/_apis/public/gallery/publisher/DavidAnson/extension/vscode-markdownlint/0.49.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-markdownlint-0.49.0.zip";
      sha256 = "sha256-Mh/OoRK410aXEr3sK2CYFDsXGSqFT+JOWi9jHOdK01Y=";
    };
    name = "vscode-markdownlint";
    publisher = "DavidAnson";
  };
  vscode-extensions-vscode-ruby = {
    pname = "vscode-extensions-vscode-ruby";
    version = "0.28.0";
    src = fetchurl {
      url = "https://wingrunr21.gallery.vsassets.io/_apis/public/gallery/publisher/wingrunr21/extension/vscode-ruby/0.28.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-ruby-0.28.0.zip";
      sha256 = "sha256-H3f1+c31x+lgCzhgTb0uLg9Bdn3pZyJGPPwfpCYrS70=";
    };
    name = "vscode-ruby";
    publisher = "wingrunr21";
  };
  vscode-extensions-zeek = {
    pname = "vscode-extensions-zeek";
    version = "0.6.0";
    src = fetchurl {
      url = "https://aeppert.gallery.vsassets.io/_apis/public/gallery/publisher/aeppert/extension/bro/0.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "bro-0.6.0.zip";
      sha256 = "sha256-+wISGCtGq/l058dOaAKlD3pGknP2ksekS1Rgmax5QgU=";
    };
    name = "bro";
    publisher = "aeppert";
  };
}
