# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  HPI = {
    pname = "HPI";
    version = "0.3.20220607";
    src = fetchurl {
      url = "https://pypi.io/packages/source/H/HPI/HPI-0.3.20220607.tar.gz";
      sha256 = "sha256-GME0Z+TH/6U+smFkuk1sT8UBzlySv5/yGhb42Kiaj8w=";
    };
  };
  StevenBlack-hosts = {
    pname = "StevenBlack-hosts";
    version = "ddcdde5e8fa97fd179033d9e75544c525cdcf2c7";
    src = fetchFromGitHub ({
      owner = "StevenBlack";
      repo = "hosts";
      rev = "ddcdde5e8fa97fd179033d9e75544c525cdcf2c7";
      fetchSubmodules = false;
      sha256 = "sha256-tCbqhnA2eXLU9ceI0Mfmzx+y5IDgFUNHdrqEs5id4lg=";
    });
    date = "2023-01-24";
  };
  acl-compat = {
    pname = "acl-compat";
    version = "cac1d6920998ddcbee8310a873414732e707d8e5";
    src = fetchgit {
      url = "https://git.code.sf.net/p/portableaserve/git";
      rev = "cac1d6920998ddcbee8310a873414732e707d8e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-CvfiudyBNYQsyPFy05kjbhGVtwl56wKPAllqgi6uZio=";
    };
    date = "2019-07-20";
  };
  activity-watch-mode = {
    pname = "activity-watch-mode";
    version = "789ec3425623e43a29755e8daaa02305df8da8ed";
    src = fetchgit {
      url = "https://github.com/pauldub/activity-watch-mode";
      rev = "789ec3425623e43a29755e8daaa02305df8da8ed";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-OoZSAiPX6mCiiETYWgl6H47AtQaLR0h8Q78fbr6kxU4=";
    };
    date = "2022-01-11";
  };
  age-plugin-trezor = {
    pname = "age-plugin-trezor";
    version = "1a89e1aec4aa6ee85987883146c5decd42a47a39";
    src = fetchFromGitHub ({
      owner = "romanz";
      repo = "age-plugin-trezor";
      rev = "1a89e1aec4aa6ee85987883146c5decd42a47a39";
      fetchSubmodules = false;
      sha256 = "sha256-EXhbCjIl5xDfxOZIQEDWHSFnWabwlVC5EYWk4ezAXy8=";
    });
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2021-01-01";
  };
  all-the-icons = {
    pname = "all-the-icons";
    version = "51bf77da1ebc3c199dfc11f54c0dce67559f5f40";
    src = fetchgit {
      url = "https://github.com/domtronn/all-the-icons.el";
      rev = "51bf77da1ebc3c199dfc11f54c0dce67559f5f40";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-vi0FPG7LUd3T0YQZMoPqXE1UBGNDA3EVj409d2FVv8U=";
    };
    date = "2022-09-30";
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "c8536fa43f0e8b506e9dd1a91e2f01ceccca0251";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "c8536fa43f0e8b506e9dd1a91e2f01ceccca0251";
      fetchSubmodules = false;
      sha256 = "sha256-dQd1/RYH/j3R7MgMoz3EZ2Nxf3XXYCTKxBvi+cvyV2g=";
    });
    date = "2022-12-11";
  };
  brig = {
    pname = "brig";
    version = "6b7eccf8fcbd907fc759f8ca8aa814df8499e2ed";
    src = fetchFromGitHub ({
      owner = "sahib";
      repo = "brig";
      rev = "6b7eccf8fcbd907fc759f8ca8aa814df8499e2ed";
      fetchSubmodules = false;
      sha256 = "sha256-lCXSeTIZcIcVcblm9BTUMqTfxO7+BHYQNv6/RlPq14A=";
    });
    vendorSha256 = "sha256-pFrrMq7VFCwt8KRgJApCq8lPYv0P8hIUOxKJMN9QR0U=";
    date = "2021-03-23";
  };
  chemacs = {
    pname = "chemacs";
    version = "c2d700b784c793cc82131ef86323801b8d6e67bb";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2";
      rev = "c2d700b784c793cc82131ef86323801b8d6e67bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/WtacZPr45lurS0hv+W8UGzsXY3RujkU5oGGGqjqG0Q=";
    };
    date = "2023-01-20";
  };
  cl-hash-util = {
    pname = "cl-hash-util";
    version = "91d17d3e9208db9438b72bb60037644fd79fb497";
    src = fetchFromGitHub ({
      owner = "orthecreedence";
      repo = "cl-hash-util";
      rev = "91d17d3e9208db9438b72bb60037644fd79fb497";
      fetchSubmodules = false;
      sha256 = "sha256-6iDMXSS3OLHqDayYpCMboPKSxXzoEYxZETygVgABzTY=";
    });
    date = "2019-01-05";
  };
  cl-shellwords = {
    pname = "cl-shellwords";
    version = "313576b9f6b925cbbc3dcf5e49e8f47c9c1b46bc";
    src = fetchFromGitHub ({
      owner = "jorams";
      repo = "cl-shellwords";
      rev = "313576b9f6b925cbbc3dcf5e49e8f47c9c1b46bc";
      fetchSubmodules = false;
      sha256 = "sha256-9hKq54YOOEE3Vc/9LVUnqvcw/1G1rpcUVL+8GKJlqEY=";
    });
    date = "2015-09-20";
  };
  cl-strings = {
    pname = "cl-strings";
    version = "93ec4177fc51f403a9f1ef0a8933f36d917f2140";
    src = fetchFromGitHub ({
      owner = "diogoalexandrefranco";
      repo = "cl-strings";
      rev = "93ec4177fc51f403a9f1ef0a8933f36d917f2140";
      fetchSubmodules = false;
      sha256 = "sha256-UpXjI9KsWvOhsjGSo1zVMNlD1I4Pwu9+cZoD60jREMk=";
    });
    date = "2021-03-08";
  };
  cl-syslog = {
    pname = "cl-syslog";
    version = "f62d524874616383650e30f7f23320005fd310c1";
    src = fetchFromGitHub ({
      owner = "lhope";
      repo = "cl-syslog";
      rev = "f62d524874616383650e30f7f23320005fd310c1";
      fetchSubmodules = false;
      sha256 = "sha256-rH0zOgXR3BixtVaqcYPhIfZBjqYgWnqrORQfr1mBqFM=";
    });
    date = "2006-11-28";
  };
  color-rg = {
    pname = "color-rg";
    version = "beb875f3cab590b5113a33579c3b68c73bd56ffd";
    src = fetchgit {
      url = "https://github.com/manateelazycat/color-rg";
      rev = "beb875f3cab590b5113a33579c3b68c73bd56ffd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Ucu7PU4DyhmMNw6bwPaDHRCdPCkaj9IDQfGaJP3wj+0=";
    };
    date = "2022-11-11";
  };
  console-solarized = {
    pname = "console-solarized";
    version = "26929b5e303703ec527b6f6e4569f351d9831e52";
    src = fetchFromGitHub ({
      owner = "adeverteuil";
      repo = "console-solarized";
      rev = "26929b5e303703ec527b6f6e4569f351d9831e52";
      fetchSubmodules = false;
      sha256 = "sha256-QMxhuDuVHgw8+DpQAavtC3Dyg4rBmbrYoA8tKtamy3Y=";
    });
    date = "2018-10-28";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "45014a9b61e83464c2fc1c65f417391b723a9246";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "45014a9b61e83464c2fc1c65f417391b723a9246";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-mJ7mW/2+e32oIFJWdHmnZjxTiJq4pU0ZvdA4RxR8wjI=";
    };
    date = "2023-01-18";
  };
  crystalline = {
    pname = "crystalline";
    version = "25074d9e0975ed6175f965c5ce584d7b12a366a1";
    src = fetchgit {
      url = "https://github.com/elbywan/crystalline";
      rev = "25074d9e0975ed6175f965c5ce584d7b12a366a1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-G2Jrp6r8OStN69KggwMqSWnjpq+zWerTtnpz34cY6tk=";
    };
    date = "2023-01-13";
  };
  dbus = {
    pname = "dbus";
    version = "f4d1a99cfb38ded33f4fb58bb5522815f530b3c3";
    src = fetchgit {
      url = "https://github.com/death/dbus";
      rev = "f4d1a99cfb38ded33f4fb58bb5522815f530b3c3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SnjJfvQtsWMgHl8EZFhhv8NtMXRi8lCXiN7kg0kghb8=";
    };
    date = "2020-06-03";
  };
  dbus-listen = {
    pname = "dbus-listen";
    version = "e7aeedfbcdc18e3ea2d45cf6931e38d350096f2f";
    src = fetchgit {
      url = "https://github.com/voobscout/dbus-listen";
      rev = "e7aeedfbcdc18e3ea2d45cf6931e38d350096f2f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WU3e7F0iNrxiS7WXzNbxnBp4oIru2pLihKbVIR236J4=";
    };
    date = "2022-09-09";
  };
  doom-emacs = {
    pname = "doom-emacs";
    version = "e96624926d724aff98e862221422cd7124a99c19";
    src = fetchgit {
      url = "https://github.com/hlissner/doom-emacs";
      rev = "e96624926d724aff98e862221422cd7124a99c19";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-GFTUnhPGOUcmIFeYT7zfwEPGoPLsA5ZhkSExVf0mSGU=";
    };
    date = "2023-01-01";
  };
  freedos = {
    pname = "freedos";
    version = "1.3-rc5";
    src = fetchurl {
      url = "https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/previews/1.3-rc5/FD13-LiveCD.zip";
      sha256 = "sha256-SO3BVISYqb/1Mm0iFgR59qooD3rHhQBvP2LAyEVESXo=";
    };
  };
  getoptions = {
    pname = "getoptions";
    version = "a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa";
    src = fetchFromGitHub ({
      owner = "ko1nksm";
      repo = "getoptions";
      rev = "a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa";
      fetchSubmodules = false;
      sha256 = "sha256-MJ4UUDmd+yykvRjgxx8MRZwlLNauDb8Bh8lS0QvkG+U=";
    });
    date = "2022-07-03";
  };
  git-get = {
    pname = "git-get";
    version = "8cd27a8f629317bd27432f2e9a4bd00561b3b21e";
    src = fetchFromGitHub ({
      owner = "grdl";
      repo = "git-get";
      rev = "8cd27a8f629317bd27432f2e9a4bd00561b3b21e";
      fetchSubmodules = false;
      sha256 = "sha256-dBZNrhg4df7NDECq8B333dY/7OXEyPIByD7YHdV9moo=";
    });
    vendorSha256 = "05k6w4knk7fdjm9qm272nlrk47rzjr18g0fp4j57f5ncq26cxr8b";
    date = "2021-08-07";
  };
  git-pull-request-mirror = {
    pname = "git-pull-request-mirror";
    version = "3d342363b0e1f2da4e59ac01baf4601bcf233bf9";
    src = fetchFromGitHub ({
      owner = "google";
      repo = "git-pull-request-mirror";
      rev = "3d342363b0e1f2da4e59ac01baf4601bcf233bf9";
      fetchSubmodules = false;
      sha256 = "sha256-OMtRSGRB1xRk3L3sIfEpagDQHNWNJBBOE5tuW7ic4Y4=";
    });
    vendorSha256 = "0789v1r6my256pncs0105yji28ifchj6ppfiy8gavglgclq3cgvn";
    date = "2020-05-13";
  };
  git-remote-ipfs = {
    pname = "git-remote-ipfs";
    version = "12b3f421c19eb5548ae76b8c79c9581a428329e0";
    src = fetchFromGitHub ({
      owner = "bqv";
      repo = "git-remote-ipfs";
      rev = "12b3f421c19eb5548ae76b8c79c9581a428329e0";
      fetchSubmodules = false;
      sha256 = "sha256-59zv362KfuW1Lki9vfwe9fJfdm6o0+DTPDbI/L+Ugsk=";
    });
    vendorSha256 = "hkenInaS6PFnu/Z0oz32Y4B4BmM5+l5AB2/K1f/LxqA=";
    date = "2021-01-24";
  };
  gitea-tea = {
    pname = "gitea-tea";
    version = "6a848cb72a1a149d8c0a91c57657bcaca51e3978";
    src = fetchgit {
      url = "https://gitea.com/gitea/tea";
      rev = "6a848cb72a1a149d8c0a91c57657bcaca51e3978";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-hhdNdGdMMlvaC7efz60LI0y5o8TjG3o+V+fSoHnyYyQ=";
    };
    date = "2022-10-31";
  };
  gpg-hd = {
    pname = "gpg-hd";
    version = "b1d7c2d8d5bdf6de67e81c9930675c06e7a51b48";
    src = fetchFromGitHub ({
      owner = "Logicwax";
      repo = "gpg-hd";
      rev = "b1d7c2d8d5bdf6de67e81c9930675c06e7a51b48";
      fetchSubmodules = false;
      sha256 = "sha256-0t91FkYOEkqa/tjOZR3MIE2q5cI7+UwJfXBDDip1/uQ=";
    });
    date = "2022-03-02";
  };
  hug = {
    pname = "hug";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/h/hug/hug-2.6.1.tar.gz";
      sha256 = "sha256-sO2s4qy2GIc3ecnObs+RZdtU/vlcIiYvVwD83Z/rrsk=";
    };
  };
  ipxe = {
    pname = "ipxe";
    version = "2d180ce233f6eae8d0df279e5cbf134f547f604c";
    src = fetchgit {
      url = "https://github.com/ipxe/ipxe";
      rev = "2d180ce233f6eae8d0df279e5cbf134f547f604c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PKTxFVUT86i1j3ORqRV7S5jk28DT0mxxzx/ez3dPQRM=";
    };
    date = "2023-01-25";
  };
  kea-ma = {
    pname = "kea-ma";
    version = "4.4.2";
    src = fetchurl {
      url = "https://dl.cloudsmith.io/public/isc/keama/deb/ubuntu/pool/bionic/main/i/is/isc-dhcp-keama_4.4.2_amd64.deb";
      sha256 = "sha256-8PfGxIh5IhJfys5JlG3nTT1A8t+RP/rQBQ/SL9CojsA=";
    };
  };
  ledger-live-desktop = {
    pname = "ledger-live-desktop";
    version = "2.51.0";
    src = fetchurl {
      url = "https://download.live.ledger.com/ledger-live-desktop-2.51.0-linux-x86_64.AppImage";
      sha256 = "sha256-qpgzGJsj7hrrK2i+xP0T+hcw7WMlGBILbHVJBHD5duo=";
    };
  };
  listopia = {
    pname = "listopia";
    version = "2d2a1a3c35580252ca0085e15ebf625f73230d60";
    src = fetchFromGitHub ({
      owner = "Dimercel";
      repo = "listopia";
      rev = "2d2a1a3c35580252ca0085e15ebf625f73230d60";
      fetchSubmodules = false;
      sha256 = "sha256-IEoPmF0QC1S6xF/enlqy1rDX8qi/2bvacxWpCHaro0k=";
    });
    date = "2021-03-17";
  };
  lorri = {
    pname = "lorri";
    version = "803fadb70907dca3afd93176aa9bc771be80d471";
    src = fetchFromGitHub ({
      owner = "nix-community";
      repo = "lorri";
      rev = "803fadb70907dca3afd93176aa9bc771be80d471";
      fetchSubmodules = false;
      sha256 = "sha256-eR8i7pSUW/I7wCR+vMZLC046paBqxOsP7E8L/AlORtw=";
    });
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2022-12-30";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  masterpdfeditor = {
    pname = "masterpdfeditor";
    version = "5.9.06";
    src = fetchurl {
      url = "https://code-industry.net/public/master-pdf-editor-5.9.06-qt5.x86_64.tar.gz";
      sha256 = "sha256-F9MeZhCMGE/z7v70lC/Bt1vPEuRMyrGBLT/gMH2gm3I=";
    };
  };
  nebula-openwrt-armv7l = {
    pname = "nebula-openwrt-armv7l";
    version = "1.5.2";
    src = fetchurl {
      url = "https://github.com/slackhq/nebula/releases/download/v1.5.2/nebula-linux-arm-7.tar.gz";
      sha256 = "sha256-h8n/FvonqWXKa04E78jwbqCAbdrSJhlYKxvXrh3j63k=";
    };
  };
  nix-index = {
    pname = "nix-index";
    version = "5f98881b1ed27ab6656e6d71b534f88430f6823a";
    src = fetchFromGitHub ({
      owner = "bennofs";
      repo = "nix-index";
      rev = "5f98881b1ed27ab6656e6d71b534f88430f6823a";
      fetchSubmodules = false;
      sha256 = "sha256-U6aYz3lqZ4NVEGEWiti1i0FyqEo4bUjnTAnA73DPnNU=";
    });
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2023-01-17";
  };
  nix-linter = {
    pname = "nix-linter";
    version = "ecdd50750fd3ffaff83c0637474b884a0c38f8b9";
    src = fetchgit {
      url = "https://github.com/Synthetica9/nix-linter";
      rev = "ecdd50750fd3ffaff83c0637474b884a0c38f8b9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-wWkRak3bQvE5dY/CXqNelK3XIoHOk48m3pQHWJWKpkI=";
    };
    date = "2021-07-20";
  };
  nix-mode = {
    pname = "nix-mode";
    version = "9fc77498563771a23207b14714140c77b36d51df";
    src = fetchgit {
      url = "https://github.com/NixOS/nix-mode";
      rev = "9fc77498563771a23207b14714140c77b36d51df";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-8BGfy0R8vKfBoXIUymaPYuWdQK3I4mVRDC5R+GCEfrQ=";
    };
    ename = "nix-mode";
    date = "2023-01-19";
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchFromGitHub ({
      owner = "spwhitt";
      repo = "nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      sha256 = "sha256-TWgo56l+FBXssOYWlAfJ5j4pOHNmontOEolcGdihIJs=";
    });
    date = "2021-02-22";
  };
  numix-solarized-gtk-theme-git = {
    pname = "numix-solarized-gtk-theme-git";
    version = "905bfa3771835e8113b6ec131280c1eadcd6bbbf";
    src = fetchgit {
      url = "https://github.com/Ferdi265/numix-solarized-gtk-theme.git";
      rev = "905bfa3771835e8113b6ec131280c1eadcd6bbbf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PUa5s7i3Xz56VQ2n4FuvwDW9l9L/KEWIg3aAuAyDEOY=";
    };
    date = "2021-10-15";
  };
  okteto-bin = {
    pname = "okteto-bin";
    version = "2.11.1";
    src = fetchurl {
      url = "https://github.com/okteto/okteto/releases/download/2.11.1/okteto-Linux-x86_64";
      sha256 = "sha256-+HKE6Dyych90O3dNMCO5az3UOJzLflhWCB7wBw98Y3o=";
    };
  };
  open-in-editor = {
    pname = "open-in-editor";
    version = "08057f04a8d025a44974cb83770851b0b9149f82";
    src = fetchgit {
      url = "https://github.com/karlicoss/open-in-editor";
      rev = "08057f04a8d025a44974cb83770851b0b9149f82";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-x7MqX6GLKsZahXAxbw6mVZ5gQP/Sar9EiHJgqhABW9s=";
    };
    date = "2021-02-28";
  };
  org-pretty-table = {
    pname = "org-pretty-table";
    version = "7bd68b420d3402826fea16ee5099d04aa9879b78";
    src = fetchgit {
      url = "https://github.com/Fuco1/org-pretty-table";
      rev = "7bd68b420d3402826fea16ee5099d04aa9879b78";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-TlPneTJVhY11HVShqYLxGgezDrpk5cx1IndXFAZJutM=";
    };
    date = "2021-11-01";
  };
  org-protocol-capture-html = {
    pname = "org-protocol-capture-html";
    version = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
    src = fetchgit {
      url = "https://github.com/alphapapa/org-protocol-capture-html";
      rev = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-X+t8E+0Bxtl6YMU0SwA/vRD8kn1lSXd2PcBhIY001Xo=";
    };
    date = "2022-10-05";
  };
  orgparse = {
    pname = "orgparse";
    version = "0.3.2";
    src = fetchurl {
      url = "https://pypi.io/packages/source/o/orgparse/orgparse-0.3.2.tar.gz";
      sha256 = "sha256-RRBQ55rLelHGXcmbkJXq5NUL1ZhUE1T552PLTL31mlU=";
    };
  };
  pam_u2f = {
    pname = "pam_u2f";
    version = "1.2.1";
    src = fetchurl {
      url = "https://developers.yubico.com/pam-u2f/Releases/pam_u2f-1.2.1.tar.gz";
      sha256 = "sha256-cOdBvKGXtktPvo3R9tV84ritWMp4Y1LFJfPy1EEliUw=";
    };
  };
  pam_usb = {
    pname = "pam_usb";
    version = "ef5f774e4c6b3fc6664d98c1fd104abf0a075e98";
    src = fetchgit {
      url = "https://github.com/mcdope/pam_usb";
      rev = "ef5f774e4c6b3fc6664d98c1fd104abf0a075e98";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ne/RIr26CbQHt9fC+y9jnPE1n6I/sOYBCWYoyYZmaTY=";
    };
    date = "2022-09-30";
  };
  paper-store = {
    pname = "paper-store";
    version = "638a495e9b56262b981c7b19e82967495bdd1278";
    src = fetchgit {
      url = "https://github.com/nurupo/paper-store";
      rev = "638a495e9b56262b981c7b19e82967495bdd1278";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-aPxao4BZ15m6pEWPYhftbN/6Witu2GSydPforjt2sro=";
    };
    date = "2019-07-05";
  };
  pass-secret-service = {
    pname = "pass-secret-service";
    version = "fadc09be718ae1e507eeb8719f3a2ea23edb6d7a";
    src = fetchgit {
      url = "https://github.com/mdellweg/pass_secret_service.git";
      rev = "fadc09be718ae1e507eeb8719f3a2ea23edb6d7a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lrNU5bkG4/fMu5rDywfiI8vNHyBsMf/fiWIeEHug03c=";
    };
    date = "2022-07-18";
  };
  pbkdf2-sha512 = {
    pname = "pbkdf2-sha512";
    version = "802489fbace4b7c75fc47937bb639006bae7e608";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/NixOS/nixpkgs/master/nixos/modules/system/boot/pbkdf2-sha512.c";
      sha256 = "sha256-OelyIsDDto6Ir22YY/UM+r9EBx6K8TNdjM3efzUJxE8=";
    };
    date = "2023-01-27";
  };
  promnesia = {
    pname = "promnesia";
    version = "a716d74d7b8f1447295b5c89d4bcee48a645376e";
    src = fetchFromGitHub ({
      owner = "karlicoss";
      repo = "promnesia";
      rev = "a716d74d7b8f1447295b5c89d4bcee48a645376e";
      fetchSubmodules = false;
      sha256 = "sha256-ewIiPMJEcB9LalFoA+qczGOlrcajcg9RNIuJ9Xt2R0s=";
    });
    date = "2023-01-25";
  };
  quicklisp = {
    pname = "quicklisp";
    version = "latest";
    src = fetchurl {
      url = "https://beta.quicklisp.org/quicklisp.lisp";
      sha256 = "sha256-SnpcKuvgcWQXBHhUJnOX4kpE0MzglhJ0EenOnM/rLBc=";
    };
  };
  rage = {
    pname = "rage";
    version = "3ff541a0a59864b782aeaca4d33cee1c8d61c2e9";
    src = fetchgit {
      url = "https://github.com/str4d/rage";
      rev = "3ff541a0a59864b782aeaca4d33cee1c8d61c2e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-haRRs/I0Oajx7ptF1o1/IJqQOQ2NmdoMYYnDdfupVUE=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2022-10-28";
  };
  rainbowsh = {
    pname = "rainbowsh";
    version = "1bcf6e44a0d9694da4d3fa637644e5da5a7250ca";
    src = fetchFromGitHub ({
      owner = "xr09";
      repo = "rainbow.sh";
      rev = "1bcf6e44a0d9694da4d3fa637644e5da5a7250ca";
      fetchSubmodules = false;
      sha256 = "sha256-F+Nabc/Fe5ET6lSkdll5YH/mEpKp3OlpaGk+u0rQpPQ=";
    });
    date = "2022-08-24";
  };
  remmina = {
    pname = "remmina";
    version = "v1.4.27";
    src = fetchgit {
      url = "https://gitlab.com/Remmina/Remmina";
      rev = "v1.4.27";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-zodC8RSWiVeYaGjfwxemzpDFb4CtWElnFGKE5nezIuE=";
    };
  };
  rtl88x2bu = {
    pname = "rtl88x2bu";
    version = "a2ac3b220db7ac38fb85d5f24730429ec2e68910";
    src = fetchFromGitHub ({
      owner = "RinCat";
      repo = "RTL88x2BU-Linux-Driver";
      rev = "a2ac3b220db7ac38fb85d5f24730429ec2e68910";
      fetchSubmodules = false;
      sha256 = "sha256-9f7H3e2MFW97VRpROfvNmCJdiuEzXjKcGd3ufqliqBI=";
    });
    date = "2022-12-13";
  };
  rubygems-huginn = {
    pname = "rubygems-huginn";
    version = "68b759a3f0874507d1871cf5c4700950579818d9";
    src = fetchFromGitHub ({
      owner = "huginn";
      repo = "huginn";
      rev = "68b759a3f0874507d1871cf5c4700950579818d9";
      fetchSubmodules = false;
      sha256 = "sha256-VcsvrJeUVUgr6yo+x/+HvdwPqCKaqZLImJIE9BF2IxE=";
    });
  };
  rubygems-nodejs-16-10-0 = {
    pname = "rubygems-nodejs-16-10-0";
    version = "v16.10.0";
    src = fetchFromGitHub ({
      owner = "nodejs";
      repo = "node";
      rev = "v16.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-YHhjHHJdRcKwok+EjIOHvtnr1OtZ44Ua1sdhnbV4OgI=";
    });
  };
  rubygems-solargraph = {
    pname = "rubygems-solargraph";
    version = "v0.44.2";
    src = fetchFromGitHub ({
      owner = "castwide";
      repo = "solargraph";
      rev = "v0.44.2";
      fetchSubmodules = false;
      sha256 = "sha256-TTUXO4E4U7abctoe9ys6SUete77CfzGq4YJOegWgNkw=";
    });
  };
  shellspec = {
    pname = "shellspec";
    version = "f800240b606ed8d60f27ca687400836c0083e76a";
    src = fetchFromGitHub ({
      owner = "shellspec";
      repo = "shellspec";
      rev = "f800240b606ed8d60f27ca687400836c0083e76a";
      fetchSubmodules = false;
      sha256 = "sha256-PyZBc7bmycV02nTpoDaA40m4DA1IuDmb/eCd3+RAp0o=";
    });
    date = "2022-05-04";
  };
  shflags = {
    pname = "shflags";
    version = "7d0daf1b3b3163c34e0108cdb439e2cd2f148152";
    src = fetchFromGitHub ({
      owner = "kward";
      repo = "shflags";
      rev = "7d0daf1b3b3163c34e0108cdb439e2cd2f148152";
      fetchSubmodules = false;
      sha256 = "sha256-t+6QCtpntU+2rjUlvCpGgsjU8ibWDHUP3MRGeAaRVbo=";
    });
    date = "2020-04-13";
  };
  spacemacs = {
    pname = "spacemacs";
    version = "2c5491437024b6b744cfe98ff49a84d5f79afc34";
    src = fetchgit {
      url = "https://github.com/syl20bnr/spacemacs";
      rev = "2c5491437024b6b744cfe98ff49a84d5f79afc34";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-oqLB1Ii/wRfOcCcaystF9FR+sAPU9+anGNYTAjIZb8E=";
    };
    date = "2023-01-26";
  };
  stumpwm = {
    pname = "stumpwm";
    version = "189a730f73266999d5b8f992faf939c11d7815ad";
    src = fetchFromGitHub ({
      owner = "stumpwm";
      repo = "stumpwm";
      rev = "189a730f73266999d5b8f992faf939c11d7815ad";
      fetchSubmodules = false;
      sha256 = "sha256-jPxMo3QfqfSYTkKYnCf6CQhkSJrX90p70amSXynBxnE=";
    });
  };
  stumpwm-contrib = {
    pname = "stumpwm-contrib";
    version = "4613a956add7a17986a3b26c341229466cd13f1d";
    src = fetchFromGitHub ({
      owner = "stumpwm";
      repo = "stumpwm-contrib";
      rev = "4613a956add7a17986a3b26c341229466cd13f1d";
      fetchSubmodules = false;
      sha256 = "sha256-334N/bV/S7odCloCN+uPCCiz8/Sp0x7Nj6pqXNoWEL0=";
    });
    date = "2022-12-16";
  };
  stumpwm-git = {
    pname = "stumpwm-git";
    version = "9b5e0cfd19d0dfb18e284ac140431a2685afbe3e";
    src = fetchFromGitHub ({
      owner = "stumpwm";
      repo = "stumpwm";
      rev = "9b5e0cfd19d0dfb18e284ac140431a2685afbe3e";
      fetchSubmodules = false;
      sha256 = "sha256-TC7R7aLpylRTTTIU2ZRmVWZUxeDK61wSOBMPCH+/mFI=";
    });
    asd = "stumpwm";
    system = "stumpwm";
    date = "2022-12-15";
  };
  trezor-agent = {
    pname = "trezor-agent";
    version = "v0.14.5";
    src = fetchFromGitHub ({
      owner = "romanz";
      repo = "trezor-agent";
      rev = "v0.14.5";
      fetchSubmodules = false;
      sha256 = "sha256-RISAy0efdatr9u4CWNRGnlffkC8ksw1NyRpJWKwqz+s=";
    });
  };
  trezor-agent-subkeys = {
    pname = "trezor-agent-subkeys";
    version = "61dee859d49795bba0030b108dfc36963f4143cf";
    src = fetchgit {
      url = "https://github.com/jrruethe/trezor-agent";
      rev = "61dee859d49795bba0030b108dfc36963f4143cf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-llOdxTCKNhmiXG0dsa8cGpyhwUI+u9fEBPG0X88OTHQ=";
    };
    date = "2021-09-29";
  };
  trezor-gpg-pinentry-tk = {
    pname = "trezor-gpg-pinentry-tk";
    version = "0.0.10";
    src = fetchurl {
      url = "https://pypi.io/packages/source/t/trezor-gpg-pinentry-tk/trezor-gpg-pinentry-tk-0.0.10.tar.gz";
      sha256 = "sha256-h/NJKbKBP5Sbq0BYJes1h2ka2/k2gSUr564qOQZeAc4=";
    };
  };
  uhk-agent = {
    pname = "uhk-agent";
    version = "2.1.1";
    src = fetchurl {
      url = "https://github.com/UltimateHackingKeyboard/agent/releases/download/v2.1.1/UHK.Agent-2.1.1-linux-x86_64.AppImage";
      sha256 = "sha256-NhDHwQeh+zbA7XykriSMaygNm1SorMd+yy/m6sPgAhg=";
    };
  };
  vgo2nix = {
    pname = "vgo2nix";
    version = "7641c5f139f7ebe33dd76e24f2c15a7c592c9ddd";
    src = fetchgit {
      url = "https://github.com/nix-community/vgo2nix";
      rev = "7641c5f139f7ebe33dd76e24f2c15a7c592c9ddd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6anZFfJe1Dw5LvwwR6e0EGtOrjwAQTHEdarbcMnTDEs=";
    };
    date = "2022-08-24";
  };
  xxhash2mac = {
    pname = "xxhash2mac";
    version = "f1013aba4892edd9b2467db764de20fa2b98c251";
    src = fetchgit {
      url = "https://github.com/njkli/xxhash2mac";
      rev = "f1013aba4892edd9b2467db764de20fa2b98c251";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lU7CbcP48POPKD8Pibn4qxFCIGkiAbY/fC6irXAO4TU=";
    };
    date = "2022-03-22";
  };
  zero-ui = {
    pname = "zero-ui";
    version = "8785b94392e5de87b21fa93c81752ef67acc10f1";
    src = fetchgit {
      url = "https://github.com/dec0dOS/zero-ui";
      rev = "8785b94392e5de87b21fa93c81752ef67acc10f1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Db/z3pEk6eI9J0/NRh8XFFF3s6nSUTTYZLw28qE9PFE=";
    };
    date = "2022-12-30";
  };
  zeronsd = {
    pname = "zeronsd";
    version = "6105c6d565ae4d6c371f631e688b28ff9066077a";
    src = fetchFromGitHub ({
      owner = "voobscout";
      repo = "zeronsd";
      rev = "6105c6d565ae4d6c371f631e688b28ff9066077a";
      fetchSubmodules = false;
      sha256 = "sha256-CYMaZ8mL4S+kDpS5baEc3AzyfctIzZgyL87Ps1ekclk=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./zeronsd-6105c6d565ae4d6c371f631e688b28ff9066077a/Cargo.lock;
      outputHashes = {
        
      };
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2022-10-30";
  };
  zsh-plugin_aw-watcher-shell = {
    pname = "zsh-plugin_aw-watcher-shell";
    version = "9dfe5199b10f00454c95dea9a33d9873e9bf9786";
    src = fetchgit {
      url = "https://github.com/nickbradley/aw-watcher-shell";
      rev = "9dfe5199b10f00454c95dea9a33d9873e9bf9786";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qPVAekgDrYoej4ycnJb+9Sz04oHfajC3MOgKxhyv7VE=";
    };
    date = "2019-07-19";
  };
  zsh-plugin_clipboard = {
    pname = "zsh-plugin_clipboard";
    version = "7fbd15150fe0fc84a34b6aa9e31c5589de3c9ffc";
    src = fetchgit {
      url = "https://github.com/zpm-zsh/clipboard";
      rev = "7fbd15150fe0fc84a34b6aa9e31c5589de3c9ffc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-BaYYzl6JArfPWASJtzk44scGejwgyT5+W94ugVDCV3I=";
    };
    date = "2022-06-24";
  };
  zsh-plugin_k = {
    pname = "zsh-plugin_k";
    version = "e2bfbaf3b8ca92d6ffc4280211805ce4b8a8c19e";
    src = fetchgit {
      url = "https://github.com/supercrabtree/k";
      rev = "e2bfbaf3b8ca92d6ffc4280211805ce4b8a8c19e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-32rJjBzqS2e6w/L78KMNwQRg4E3sqqdAmb87XEhqbRQ=";
    };
    date = "2018-09-09";
  };
  zsh-plugin_oh-my-zsh = {
    pname = "zsh-plugin_oh-my-zsh";
    version = "e55e3f0f56ab4df21eb33e19569c295e7e5e71a4";
    src = fetchgit {
      url = "https://github.com/robbyrussell/oh-my-zsh";
      rev = "e55e3f0f56ab4df21eb33e19569c295e7e5e71a4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-gN5jjhbRxSBJiXs1DsUeMHCCsv9qSOxC4guHmjJdW7U=";
    };
    date = "2023-01-26";
  };
  zsh-plugin_tipz = {
    pname = "zsh-plugin_tipz";
    version = "594eab4642cc6dcfe063ecd51d76478bd84e2878";
    src = fetchgit {
      url = "https://github.com/molovo/tipz";
      rev = "594eab4642cc6dcfe063ecd51d76478bd84e2878";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oFZJwHYDfK4f53lhcZg6PCw2AgHxFC0CRiqiinKZz8k=";
    };
    date = "2018-05-03";
  };
  zsh-plugin_zsh-256color = {
    pname = "zsh-plugin_zsh-256color";
    version = "559fee48bb74b75cec8b9887f8f3e046f01d5d8f";
    src = fetchgit {
      url = "https://github.com/chrissicool/zsh-256color";
      rev = "559fee48bb74b75cec8b9887f8f3e046f01d5d8f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-P/pbpDJmsMSZkNi5GjVTDy7R+OxaIVZhb/bEnYQlaLo=";
    };
    date = "2022-09-13";
  };
  zsh-plugin_zsh-autoenv = {
    pname = "zsh-plugin_zsh-autoenv";
    version = "e9809c1bd28496e025ca05576f574e08e93e12e8";
    src = fetchgit {
      url = "https://github.com/Tarrasch/zsh-autoenv";
      rev = "e9809c1bd28496e025ca05576f574e08e93e12e8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SxDRldr9eqRtPQ3IWFKX0Q+vEG8Ry34PNRZ/I16aju0=";
    };
    date = "2018-09-14";
  };
  zsh-plugin_zsh-autopair = {
    pname = "zsh-plugin_zsh-autopair";
    version = "396c38a7468458ba29011f2ad4112e4fd35f78e6";
    src = fetchgit {
      url = "https://github.com/hlissner/zsh-autopair";
      rev = "396c38a7468458ba29011f2ad4112e4fd35f78e6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PXHxPxFeoYXYMOC29YQKDdMnqTO0toyA7eJTSCV6PGE=";
    };
    date = "2022-10-03";
  };
  zsh-plugin_zsh-completions = {
    pname = "zsh-plugin_zsh-completions";
    version = "54156de9cbcc807e9cdb9a7c4e6c09d4bab14536";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-completions";
      rev = "54156de9cbcc807e9cdb9a7c4e6c09d4bab14536";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2Y1e8fbEer5HtOeI7GHSie0cizKLpd0wlDVooRGO5Ng=";
    };
    date = "2023-01-26";
  };
  zsh-plugin_zsh-history-substring-search = {
    pname = "zsh-plugin_zsh-history-substring-search";
    version = "400e58a87f72ecec14f783fbd29bc6be4ff1641c";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-history-substring-search";
      rev = "400e58a87f72ecec14f783fbd29bc6be4ff1641c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-GSEvgvgWi1rrsgikTzDXokHTROoyPRlU0FVpAoEmXG4=";
    };
    date = "2023-01-03";
  };
  zsh-plugin_zsh-syntax-highlighting = {
    pname = "zsh-plugin_zsh-syntax-highlighting";
    version = "b2c910a85ed84cb7e5108e7cb3406a2e825a858f";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-syntax-highlighting";
      rev = "b2c910a85ed84cb7e5108e7cb3406a2e825a858f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-hEQxhpa94bU3ydOpIFtgF5NBpkl65caMWrhktWXSHZ4=";
    };
    date = "2022-11-19";
  };
  ztncui = {
    pname = "ztncui";
    version = "8fb29fa60771bdaa1e66157c7c383cb56afa0c8f";
    src = fetchgit {
      url = "https://github.com/key-networks/ztncui";
      rev = "8fb29fa60771bdaa1e66157c7c383cb56afa0c8f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/GzlyFwwxZL/lMTG3qpOd8SPrfR6TLYut6JJ+7DDv7I=";
    };
    date = "2022-01-03";
  };
}
